spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/udemy_test
    username: hector
    password: H3ct0r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8001